#!/bin/bash

echo "🎙️ Multi-Speaker Audio Transcript Generator Demo"
echo "================================================="
echo ""
echo "This system provides:"
echo "✅ Automatic speaker diarization"
echo "✅ High-quality speech-to-text transcription"
echo "✅ Precise timestamp generation"
echo "✅ Easy-to-use web interface"
echo "✅ Support for WAV and MP3 files"
echo ""
echo "🚀 Quick Start Guide:"
echo "1. Run: ./setup.sh (first time only)"
echo "2. Run: ./run.sh (starts the web interface)"
echo "3. Upload your audio file"
echo "4. Download the generated transcript"
echo ""
echo "📋 Example Output Format:"
echo "========================="
echo "00:00:00,000 --> 00:00:03,500"
echo "Speaker_1: Merhaba, hoş geldin."
echo ""
echo "00:00:03,600 --> 00:00:06,800"
echo "Speaker_2: Teşekkürler, seni görmek güzel."
echo ""
echo "🔧 Files Created:"
echo "- main.py: Core processing engine"
echo "- app.py: Streamlit web interface"  
echo "- requirements.txt: Dependencies"
echo "- setup.sh: Automated setup script"
echo "- run.sh: Quick launch script"
echo ""
echo "💡 Ready to start? Run: ./setup.sh"